---
- name: Copy docker-compose.yml
  copy:
    src: ../../../../Docker-compose.yml
    dest: "{{ bot_dir }}/docker-compose.yml"

- name: Copy Dockerfile
  copy:
    src: ../../../../Dockerfile
    dest: "{{ bot_dir }}/Dockerfile"
