version: '3.8'

services:
  bot:
    container_name: bot
    build: .
    volumes:
      - .:/bot
    env_file: .env
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge