---
- name: Deploy bot in Docker on remote server
  hosts: all
  become: true
  vars:
    bot_dir: /home/{{ ansible_user }}/bot
    env_file_path: /path/to/your/env/file  # Укажите правильный путь к .env файлу
  
  roles:
    - role: ssh
    - role: dependencies
    - role: docker
    - role: bot