---
- name: Deploy bot in Docker on remote server
  hosts: all
  become: true
  vars:
    bot_dir: /home/{{ ansible_user }}/bot
    terraform_env_path: "/home/{{ ansible_user }}/.env"
  
  roles:
    - role: ssh
    - role: dependencies
    - role: docker
    - role: bot