---
- name: Clone bot repository
  git:
    repo: 'https://github.com/flightbee/bot.git'
    dest: "{{ bot_dir }}"
    version: main
    force: yes

- name: Synchronize .env file
  copy:
    src: ../../../../.env
    dest: "{{ bot_dir }}/.env"
    owner: "{{ ansible_user }}"
    mode: '0600'

- name: Build and run Docker Compose
  shell: |
    cd {{ bot_dir }}
    docker-compose down || true
    docker-compose up -d --build
