---
- name: Clone bot repository
  git:
    repo: 'https://github.com/flightbee/bot.git'
    dest: "{{ bot_dir }}"
    version: main
    force: yes
    recursive: yes

- name: Verify docker-compose file exists
  stat:
    path: "{{ bot_dir }}/docker-compose.yml"
  register: compose_file

- name: Create base .env file with Telegram token
  copy:
    content: |
      TELEGRAM_BOT_TOKEN=8386506355:AAEW5kc-Qkz30mUxGkpWMSu4W8r3pmbRjpQ
    dest: "{{ bot_dir }}/.env"
    owner: "{{ ansible_user }}"
    mode: '0600'

- name: Check if local .env exists
  stat:
    path: "{{ env_file_path }}"
  register: local_env_file
  when: env_file_path is defined

- name: Append additional variables from local .env
  block:
    - name: Read local .env content
      command: cat "{{ env_file_path }}"
      register: local_env_content
      changed_when: false

    - name: Append content to .env
      lineinfile:
        path: "{{ bot_dir }}/.env"
        line: "{{ item }}"
        create: no
      loop: "{{ local_env_content.stdout_lines }}"
      when: item | length > 0 and not item.startswith('#')
  when:
    - env_file_path is defined
    - local_env_file.stat.exists

- name: Build and run Docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ bot_dir }}"
    build: always
    pull: always
    state: present